# Generated by Django 6.0.5 on 2026-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dot"),
    ]

    operations = [
        migrations.AddField(
            model_name="dot",
            name="teams",
            field=models.ManyToManyField(related_name="dots", to="app.team"),
        ),
    ]
