# Generated by Django 6.0.5 on 2026-05-19 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_dot_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="dot",
            name="claim_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
